### PR TITLE
Vs2015 warning fix

### PR DESCRIPTION
**Pull request by CreoValis**
These commits fix several warnings while compiling with Visual Studio 2015.

### CODE REVIEW

**Comment by redboltz** [comment]
@CreoValis , thank you for sending the PR. 

I agree with the following commit:
https://github.com/redboltz/mqtt_client_cpp/pull/82/commits/6f64159603f8a59abb52fd9f7daebc4ae9e023d7

However, I don't want to replace char to std::uint8_t.
https://github.com/redboltz/mqtt_client_cpp/pull/82/commits/509fae93aa7fbb0c9bd3ace72be21a014a11c74c

C++ standard byte stream type is `char` like http://www.cplusplus.com/reference/ostream/ostream/write/?kw=write.

I guess that keeping the type `char` and applying minimal cast solve the warnings.

VS2015 on appveyor doesn't report warnings.
https://ci.appveyor.com/project/redboltz/mqtt-client-cpp/branch/master/job/alix26l27i510k0x

Could you tell me the detail of warnings?

Sorry for my late reply.

**Comment by CreoValis** [comment]
You're right, the commit 6f64159603f8a59abb52fd9f7daebc4ae9e023d7 was overreaching. The compiler generated the following warning without it:
`include\mqtt\connect_flags.hpp(20): warning C4309: 'static_cast': truncation of constant value`

Indeed, the warning goes away if the `static_cast<char>` is replaced with a C-style cast:
`constexpr char const user_name_flag = (char)(0b10000000)` .

I'll update the PR with the new commits.

**Comment by redboltz** [comment]
@CreoValis , I merged the PR with some modification.
I added `/W3 /WX` flags on MSVC build.
I'd like to avoid C-style cast as long as I can. I study a way to avoid C4309, I choose static_cast<char> with unsigned postfix.

**Comment by CreoValis** [comment]
Thanks for Your help!

**Pull request merged**
